/*******************************************************************************************
*  This class is autogenerated from the class ActorLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Collections.Generic;
using FG.ServiceFabric.Tests.EventStoredActor.Diagnostics;
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.DataContracts;
using Microsoft.ApplicationInsights.Extensibility;
using System.Runtime.Remoting.Messaging;


namespace FG.ServiceFabric.Tests.EventStoredActor
{
	internal sealed class ActorLogger : IActorLogger
	{
	    private sealed class ScopeWrapper : IDisposable
        {
            private readonly IEnumerable<IDisposable> _disposables;

            public ScopeWrapper(IEnumerable<IDisposable> disposables)
            {
                _disposables = disposables;
            }

            public void Dispose()
            {
                Dispose(true);
                GC.SuppressFinalize(this);
            }

            private void Dispose(bool disposing)
            {
                if (disposing)
                {
                    foreach (var disposable in _disposables)
                    {
                        disposable.Dispose();
                    }
                }
            }
        }

	    private sealed class ScopeWrapperWithAction : IDisposable
        {
            private readonly Action _onStop;

            internal static IDisposable Wrap(Func<IDisposable> wrap)
            {
                return wrap();
            }

            public ScopeWrapperWithAction(Action onStop)
            {
                _onStop = onStop;
            }

            public void Dispose()
            {
                Dispose(true);
                GC.SuppressFinalize(this);
            }

            private void Dispose(bool disposing)
            {
                if (disposing)
                {
                    _onStop?.Invoke();
                }
            }
        }


		private readonly bool _autogenerated;
		private readonly string _machineName;
		private readonly Microsoft.ApplicationInsights.TelemetryClient _telemetryClient;

        public sealed class OperationHolder
        {
            public static void StartOperation(IOperationHolder<RequestTelemetry> aiOperationHolder)
            {
                OperationHolder.Current = new OperationHolder() {AIOperationHolder = aiOperationHolder};
            }

            public static IOperationHolder<RequestTelemetry> StopOperation()
            {
                var aiOperationHolder = OperationHolder.Current.AIOperationHolder;
                OperationHolder.Current = null;

                return aiOperationHolder;
            }

            private IOperationHolder<RequestTelemetry> AIOperationHolder { get; set; }

            private static readonly string ContextKey = Guid.NewGuid().ToString();

            public static OperationHolder Current
            {
                get { return (OperationHolder)CallContext.LogicalGetData(ContextKey); }
                internal set
                {
                    if (value == null)
                    {
                        CallContext.FreeNamedDataSlot(ContextKey);
                    }
                    else
                    {
                        CallContext.LogicalSetData(ContextKey, value);
                    }
                }
            }
        }

		public ActorLogger(
			bool autogenerated,
			string machineName)
		{
			_autogenerated = autogenerated;
			_machineName = machineName;
			
            _telemetryClient = new Microsoft.ApplicationInsights.TelemetryClient();
            _telemetryClient.Context.User.Id = Environment.UserName;
            _telemetryClient.Context.Session.Id = Guid.NewGuid().ToString();
            _telemetryClient.Context.Device.OperatingSystem = Environment.OSVersion.ToString();

		}

		public void FailedToSendMessage(
			Microsoft.ServiceFabric.Actors.ActorId actorId,
			System.Uri serviceUri,
			System.Exception ex)
		{
			FGServiceFabricTestsEventStoredActorEventSource.Current.FailedToSendMessage(
				_autogenerated, 
				_machineName, 
				actorId, 
				serviceUri, 
				ex
			);
			_telemetryClient.TrackException(
	            ex,
	            new System.Collections.Generic.Dictionary<string, string>()
	            {
                    { "Name", "FailedToSendMessage" },
	                {"Autogenerated", _autogenerated.ToString()},
                    {"MachineName", Environment.MachineName},
                    {"ActorId", actorId.ToString()},
                    {"ServiceUri", serviceUri.ToString()},
                    {"Message", ex.Message},
                    {"Source", ex.Source},
                    {"ExceptionTypeName", ex.GetType().FullName},
                    {"Exception", ex.AsJson()}
	            });
    
		}



		public void MessageSent(
			Microsoft.ServiceFabric.Actors.ActorId actorId,
			System.Uri serviceUri,
			string messageType)
		{
			FGServiceFabricTestsEventStoredActorEventSource.Current.MessageSent(
				_autogenerated, 
				_machineName, 
				actorId, 
				serviceUri, 
				messageType
			);
			_telemetryClient.TrackEvent(
	            nameof(MessageSent),
	            new System.Collections.Generic.Dictionary<string, string>()
	            {
	                {"Autogenerated", _autogenerated.ToString()},
                    {"MachineName", Environment.MachineName},
                    {"ActorId", actorId.ToString()},
                    {"ServiceUri", serviceUri.ToString()},
                    {"MessageType", messageType}
	            });
    
		}



		public void MessageMovedToDeadLetterQueue(
			int depth)
		{
			FGServiceFabricTestsEventStoredActorEventSource.Current.MovedToDeadLetters(
				_autogenerated, 
				_machineName, 
				depth
			);
			_telemetryClient.TrackEvent(
	            nameof(MessageMovedToDeadLetterQueue),
	            new System.Collections.Generic.Dictionary<string, string>()
	            {
	                {"Autogenerated", _autogenerated.ToString()},
                    {"MachineName", Environment.MachineName},
                    {"Depth", depth.ToString()}
	            });
    
		}



	}
}
