/*******************************************************************************************
*  This class is autogenerated from the class ActorLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Collections.Generic;
using FG.ServiceFabric.Tests.PersonActor.Diagnostics;


namespace FG.ServiceFabric.Tests.PersonActor
{
	internal sealed class ActorLogger : IActorLogger
	{
	    private sealed class ScopeWrapper : IDisposable
        {
            private readonly IEnumerable<IDisposable> _disposables;

            public ScopeWrapper(IEnumerable<IDisposable> disposables)
            {
                _disposables = disposables;
            }

            public void Dispose()
            {
                Dispose(true);
                GC.SuppressFinalize(this);
            }

            private void Dispose(bool disposing)
            {
                if (disposing)
                {
                    foreach (var disposable in _disposables)
                    {
                        disposable.Dispose();
                    }
                }
            }
        }

	    private sealed class ScopeWrapperWithAction : IDisposable
        {
            private readonly Action _onStop;

            internal static IDisposable Wrap(Func<IDisposable> wrap)
            {
                return wrap();
            }

            public ScopeWrapperWithAction(Action onStop)
            {
                _onStop = onStop;
            }

            public void Dispose()
            {
                Dispose(true);
                GC.SuppressFinalize(this);
            }

            private void Dispose(bool disposing)
            {
                if (disposing)
                {
                    _onStop?.Invoke();
                }
            }
        }


		private readonly bool _autogenerated;
		private readonly string _machineName;

		public ActorLogger(
			bool autogenerated,
			string machineName)
		{
			_autogenerated = autogenerated;
			_machineName = machineName;
		}

		public void FailedToSendMessage(
			Microsoft.ServiceFabric.Actors.ActorId actorId,
			System.Uri serviceUri,
			System.Exception ex)
		{
			FGServiceFabricTestsPersonActorEventSource.Current.FailedToSendMessage(
				_autogenerated, 
				_machineName, 
				actorId, 
				serviceUri, 
				ex
			);
    
		}


		public void MovedToDeadLetters(
			int depth)
		{
			FGServiceFabricTestsPersonActorEventSource.Current.MovedToDeadLetters(
				_autogenerated, 
				_machineName, 
				depth
			);
    
		}


	}
}
