/*******************************************************************************************
*  This class is autogenerated from the class FGServiceFabricServicesRemotingEventSource.eventsource.json
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Diagnostics.Tracing;
using System.Threading.Tasks;

namespace FG.ServiceFabric
{
	[EventSource(Name = "FG-ServiceFabric")]
	internal sealed partial class FGServiceFabricServicesRemotingEventSource : EventSource
	{
		public static readonly FGServiceFabricServicesRemotingEventSource Current = new FGServiceFabricServicesRemotingEventSource();

		static FGServiceFabricServicesRemotingEventSource()
		{
			// A workaround for the problem where ETW activities do not 
			// get tracked until Tasks infrastructure is initialized.
			// This problem will be fixed in .NET Framework 4.6.2.
			Task.Run(() => { });
		}

		// Instance constructor is private to enforce singleton semantics
		private FGServiceFabricServicesRemotingEventSource() : base() { }

		#region Keywords
		// Event keywords can be used to categorize events. 
		// Each keyword is a bit flag. A single event can be 
		// associated with multiple keywords (via EventAttribute.Keywords property).
		// Keywords must be defined as a public class named 'Keywords' 
		// inside EventSource that uses them.
		public static class Keywords
		{
			public const EventKeywords ServiceClient = (EventKeywords)0x1L;
			public const EventKeywords ServiceCommunication = (EventKeywords)0x2L;
			public const EventKeywords ServiceRemoting = (EventKeywords)0x4L;
			public const EventKeywords ServiceCommunicationAndClient = (EventKeywords)0x8L;

		}
		#endregion Keywords

		#region Tasks

		public static class Tasks
		{
			public const EventTask CallService = (EventTask)0x1L;
			public const EventTask RecieveServiceMessage = (EventTask)0x2L;

		}
		#endregion Tasks

		#region Events



		#endregion Events
	}



}