/*******************************************************************************************
*  This class is autogenerated from the class ServiceCommunicationAndClientLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Diagnostics.Tracing;
using System.Threading.Tasks;


namespace FG.ServiceFabric
{
	internal sealed partial class FGServiceFabricServicesRemotingEventSource
	{

		private const int StartCallServiceEventId = 1001;

		[Event(StartCallServiceEventId, Level = EventLevel.LogAlways, Message = "Start Call Service {1} {2} {3} {4}", Keywords = Keywords.ServiceCommunicationAndClient, Opcode = EventOpcode.Start, Task = Tasks.CallService)]
		private void StartCallService(
			string context, 
			string requestUri, 
			string serviceMethodName, 
			string serviceMessageHeaders, 
			string customServiceRequestHeader)
		{
			WriteEvent(
				StartCallServiceEventId, 
				context, 
				requestUri, 
				serviceMethodName, 
				serviceMessageHeaders, 
				customServiceRequestHeader);
		}

		[NonEvent]
		public void StartCallService(
			System.Fabric.ServiceContext context, 
			System.Uri requestUri, 
			string serviceMethodName, 
			Microsoft.ServiceFabric.Services.Remoting.V1.ServiceRemotingMessageHeaders serviceMessageHeaders, 
			FG.ServiceFabric.Services.Remoting.FabricTransport.CustomServiceRequestHeader customServiceRequestHeader)
		{
			if (this.IsEnabled())
			{
				StartCallService(
					(context).ToString(), 
					(requestUri).ToString(), 
					serviceMethodName, 
					(serviceMessageHeaders).ToString(), 
					(customServiceRequestHeader).ToString());
			}
		}


		private const int StopCallServiceEventId = 1002;

		[Event(StopCallServiceEventId, Level = EventLevel.LogAlways, Message = "Stop Call Service {1} {2} {3} {4}", Keywords = Keywords.ServiceCommunicationAndClient, Opcode = EventOpcode.Stop, Task = Tasks.CallService)]
		private void StopCallService(
			string context, 
			string requestUri, 
			string serviceMethodName, 
			string serviceMessageHeaders, 
			string customServiceRequestHeader)
		{
			WriteEvent(
				StopCallServiceEventId, 
				context, 
				requestUri, 
				serviceMethodName, 
				serviceMessageHeaders, 
				customServiceRequestHeader);
		}

		[NonEvent]
		public void StopCallService(
			System.Fabric.ServiceContext context, 
			System.Uri requestUri, 
			string serviceMethodName, 
			Microsoft.ServiceFabric.Services.Remoting.V1.ServiceRemotingMessageHeaders serviceMessageHeaders, 
			FG.ServiceFabric.Services.Remoting.FabricTransport.CustomServiceRequestHeader customServiceRequestHeader)
		{
			if (this.IsEnabled())
			{
				StopCallService(
					(context).ToString(), 
					(requestUri).ToString(), 
					serviceMethodName, 
					(serviceMessageHeaders).ToString(), 
					(customServiceRequestHeader).ToString());
			}
		}


		private const int CallServiceFailedEventId = 1003;

		[Event(CallServiceFailedEventId, Level = EventLevel.LogAlways, Message = "{5}", Keywords = Keywords.ServiceCommunicationAndClient)]
		private void CallServiceFailed(
			string context, 
			string requestUri, 
			string serviceMethodName, 
			string serviceMessageHeaders, 
			string customServiceRequestHeader, 
			string message, 
			string source, 
			string exceptionTypeName, 
			string stackTrace)
		{
			WriteEvent(
				CallServiceFailedEventId, 
				context, 
				requestUri, 
				serviceMethodName, 
				serviceMessageHeaders, 
				customServiceRequestHeader, 
				message, 
				source, 
				exceptionTypeName, 
				stackTrace);
		}

		[NonEvent]
		public void CallServiceFailed(
			System.Fabric.ServiceContext context, 
			System.Uri requestUri, 
			string serviceMethodName, 
			Microsoft.ServiceFabric.Services.Remoting.V1.ServiceRemotingMessageHeaders serviceMessageHeaders, 
			FG.ServiceFabric.Services.Remoting.FabricTransport.CustomServiceRequestHeader customServiceRequestHeader, 
			System.Exception ex)
		{
			if (this.IsEnabled())
			{
				CallServiceFailed(
					(context).ToString(), 
					(requestUri).ToString(), 
					serviceMethodName, 
					(serviceMessageHeaders).ToString(), 
					(customServiceRequestHeader).ToString(), 
					ex.Message, 
					ex.Source, 
					ex.GetType().FullName, 
					ex.StackTrace);
			}
		}


		private const int ServiceClientFailedEventId = 1004;

		[Event(ServiceClientFailedEventId, Level = EventLevel.LogAlways, Message = "{3}", Keywords = Keywords.ServiceCommunicationAndClient)]
		private void ServiceClientFailed(
			string context, 
			string requestUri, 
			string customServiceRequestHeader, 
			string message, 
			string source, 
			string exceptionTypeName, 
			string stackTrace)
		{
			WriteEvent(
				ServiceClientFailedEventId, 
				context, 
				requestUri, 
				customServiceRequestHeader, 
				message, 
				source, 
				exceptionTypeName, 
				stackTrace);
		}

		[NonEvent]
		public void ServiceClientFailed(
			System.Fabric.ServiceContext context, 
			System.Uri requestUri, 
			FG.ServiceFabric.Services.Remoting.FabricTransport.CustomServiceRequestHeader customServiceRequestHeader, 
			System.Exception ex)
		{
			if (this.IsEnabled())
			{
				ServiceClientFailed(
					(context).ToString(), 
					(requestUri).ToString(), 
					(customServiceRequestHeader).ToString(), 
					ex.Message, 
					ex.Source, 
					ex.GetType().FullName, 
					ex.StackTrace);
			}
		}


		private const int StartRequestContextEventId = 1005;

		[Event(StartRequestContextEventId, Level = EventLevel.LogAlways, Message = "Start Request Context {1}", Keywords = Keywords.ServiceCommunicationAndClient, Opcode = EventOpcode.Start)]
		private void StartRequestContext(
			string context, 
			string headers)
		{
			WriteEvent(
				StartRequestContextEventId, 
				context, 
				headers);
		}

		[NonEvent]
		public void StartRequestContext(
			System.Fabric.ServiceContext context, 
			System.Collections.Generic.IEnumerable<FG.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestHeader> headers)
		{
			if (this.IsEnabled())
			{
				StartRequestContext(
					(context).ToString(), 
					(headers).ToString());
			}
		}


		private const int StopRequestContextEventId = 1006;

		[Event(StopRequestContextEventId, Level = EventLevel.LogAlways, Message = "Stop Request Context {1}", Keywords = Keywords.ServiceCommunicationAndClient, Opcode = EventOpcode.Stop)]
		private void StopRequestContext(
			string context, 
			string headers)
		{
			WriteEvent(
				StopRequestContextEventId, 
				context, 
				headers);
		}

		[NonEvent]
		public void StopRequestContext(
			System.Fabric.ServiceContext context, 
			System.Collections.Generic.IEnumerable<FG.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestHeader> headers)
		{
			if (this.IsEnabled())
			{
				StopRequestContext(
					(context).ToString(), 
					(headers).ToString());
			}
		}


		private const int FailedRequestContextEventId = 1007;

		[Event(FailedRequestContextEventId, Level = EventLevel.LogAlways, Message = "{2}", Keywords = Keywords.ServiceCommunicationAndClient)]
		private void FailedRequestContext(
			string context, 
			string headers, 
			string message, 
			string source, 
			string exceptionTypeName, 
			string stackTrace)
		{
			WriteEvent(
				FailedRequestContextEventId, 
				context, 
				headers, 
				message, 
				source, 
				exceptionTypeName, 
				stackTrace);
		}

		[NonEvent]
		public void FailedRequestContext(
			System.Fabric.ServiceContext context, 
			System.Collections.Generic.IEnumerable<FG.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestHeader> headers, 
			System.Exception exception)
		{
			if (this.IsEnabled())
			{
				FailedRequestContext(
					(context).ToString(), 
					(headers).ToString(), 
					exception.Message, 
					exception.Source, 
					exception.GetType().FullName, 
					exception.StackTrace);
			}
		}


		private const int FailedToReadCustomServiceMessageHeaderEventId = 1008;

		[Event(FailedToReadCustomServiceMessageHeaderEventId, Level = EventLevel.LogAlways, Message = "{2}", Keywords = Keywords.ServiceCommunicationAndClient)]
		private void FailedToReadCustomServiceMessageHeader(
			string context, 
			string serviceRemotingMessageHeaders, 
			string message, 
			string source, 
			string exceptionTypeName, 
			string stackTrace)
		{
			WriteEvent(
				FailedToReadCustomServiceMessageHeaderEventId, 
				context, 
				serviceRemotingMessageHeaders, 
				message, 
				source, 
				exceptionTypeName, 
				stackTrace);
		}

		[NonEvent]
		public void FailedToReadCustomServiceMessageHeader(
			System.Fabric.ServiceContext context, 
			Microsoft.ServiceFabric.Services.Remoting.V1.ServiceRemotingMessageHeaders serviceRemotingMessageHeaders, 
			System.Exception ex)
		{
			if (this.IsEnabled())
			{
				FailedToReadCustomServiceMessageHeader(
					(context).ToString(), 
					(serviceRemotingMessageHeaders).ToString(), 
					ex.Message, 
					ex.Source, 
					ex.GetType().FullName, 
					ex.StackTrace);
			}
		}


		private const int FailedToGetServiceMethodNameEventId = 1009;

		[Event(FailedToGetServiceMethodNameEventId, Level = EventLevel.LogAlways, Message = "{4}", Keywords = Keywords.ServiceCommunicationAndClient)]
		private void FailedToGetServiceMethodName(
			string context, 
			string requestUri, 
			int interfaceId, 
			int methodId, 
			string message, 
			string source, 
			string exceptionTypeName, 
			string stackTrace)
		{
			WriteEvent(
				FailedToGetServiceMethodNameEventId, 
				context, 
				requestUri, 
				interfaceId, 
				methodId, 
				message, 
				source, 
				exceptionTypeName, 
				stackTrace);
		}

		[NonEvent]
		public void FailedToGetServiceMethodName(
			System.Fabric.ServiceContext context, 
			System.Uri requestUri, 
			int interfaceId, 
			int methodId, 
			System.Exception ex)
		{
			if (this.IsEnabled())
			{
				FailedToGetServiceMethodName(
					(context).ToString(), 
					(requestUri).ToString(), 
					interfaceId, 
					methodId, 
					ex.Message, 
					ex.Source, 
					ex.GetType().FullName, 
					ex.StackTrace);
			}
		}


		private const int StartRecieveServiceMessageEventId = 1010;

		[Event(StartRecieveServiceMessageEventId, Level = EventLevel.LogAlways, Message = "Start Recieve Service Message {1} {2} {3} {4}", Keywords = Keywords.ServiceCommunicationAndClient, Opcode = EventOpcode.Start, Task = Tasks.RecieveServiceMessage)]
		private void StartRecieveServiceMessage(
			string context, 
			string requestUri, 
			string serviceMethodName, 
			string serviceMessageHeaders, 
			string customServiceRequestHeader)
		{
			WriteEvent(
				StartRecieveServiceMessageEventId, 
				context, 
				requestUri, 
				serviceMethodName, 
				serviceMessageHeaders, 
				customServiceRequestHeader);
		}

		[NonEvent]
		public void StartRecieveServiceMessage(
			System.Fabric.ServiceContext context, 
			System.Uri requestUri, 
			string serviceMethodName, 
			Microsoft.ServiceFabric.Services.Remoting.V1.ServiceRemotingMessageHeaders serviceMessageHeaders, 
			FG.ServiceFabric.Services.Remoting.FabricTransport.CustomServiceRequestHeader customServiceRequestHeader)
		{
			if (this.IsEnabled())
			{
				StartRecieveServiceMessage(
					(context).ToString(), 
					(requestUri).ToString(), 
					serviceMethodName, 
					(serviceMessageHeaders).ToString(), 
					(customServiceRequestHeader).ToString());
			}
		}


		private const int StopRecieveServiceMessageEventId = 1011;

		[Event(StopRecieveServiceMessageEventId, Level = EventLevel.LogAlways, Message = "Stop Recieve Service Message {1} {2} {3} {4}", Keywords = Keywords.ServiceCommunicationAndClient, Opcode = EventOpcode.Stop, Task = Tasks.RecieveServiceMessage)]
		private void StopRecieveServiceMessage(
			string context, 
			string requestUri, 
			string serviceMethodName, 
			string serviceMessageHeaders, 
			string customServiceRequestHeader)
		{
			WriteEvent(
				StopRecieveServiceMessageEventId, 
				context, 
				requestUri, 
				serviceMethodName, 
				serviceMessageHeaders, 
				customServiceRequestHeader);
		}

		[NonEvent]
		public void StopRecieveServiceMessage(
			System.Fabric.ServiceContext context, 
			System.Uri requestUri, 
			string serviceMethodName, 
			Microsoft.ServiceFabric.Services.Remoting.V1.ServiceRemotingMessageHeaders serviceMessageHeaders, 
			FG.ServiceFabric.Services.Remoting.FabricTransport.CustomServiceRequestHeader customServiceRequestHeader)
		{
			if (this.IsEnabled())
			{
				StopRecieveServiceMessage(
					(context).ToString(), 
					(requestUri).ToString(), 
					serviceMethodName, 
					(serviceMessageHeaders).ToString(), 
					(customServiceRequestHeader).ToString());
			}
		}


		private const int RecieveServiceMessageFailedEventId = 1012;

		[Event(RecieveServiceMessageFailedEventId, Level = EventLevel.LogAlways, Message = "{5}", Keywords = Keywords.ServiceCommunicationAndClient)]
		private void RecieveServiceMessageFailed(
			string context, 
			string requestUri, 
			string serviceMethodName, 
			string serviceMessageHeaders, 
			string customServiceRequestHeader, 
			string message, 
			string source, 
			string exceptionTypeName, 
			string stackTrace)
		{
			WriteEvent(
				RecieveServiceMessageFailedEventId, 
				context, 
				requestUri, 
				serviceMethodName, 
				serviceMessageHeaders, 
				customServiceRequestHeader, 
				message, 
				source, 
				exceptionTypeName, 
				stackTrace);
		}

		[NonEvent]
		public void RecieveServiceMessageFailed(
			System.Fabric.ServiceContext context, 
			System.Uri requestUri, 
			string serviceMethodName, 
			Microsoft.ServiceFabric.Services.Remoting.V1.ServiceRemotingMessageHeaders serviceMessageHeaders, 
			FG.ServiceFabric.Services.Remoting.FabricTransport.CustomServiceRequestHeader customServiceRequestHeader, 
			System.Exception ex)
		{
			if (this.IsEnabled())
			{
				RecieveServiceMessageFailed(
					(context).ToString(), 
					(requestUri).ToString(), 
					serviceMethodName, 
					(serviceMessageHeaders).ToString(), 
					(customServiceRequestHeader).ToString(), 
					ex.Message, 
					ex.Source, 
					ex.GetType().FullName, 
					ex.StackTrace);
			}
		}


	}
}